apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: myapp
    kind: Deployment
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 75
